/**
 * @generated
 * This file is auto-generated. Do not edit manually.
 */

import { Func } from "@/components/docs/reference/funcs/Func";
import { ScalarFunc as ScalarFuncType } from "@/types/docs";

export default function Page() {
  return <Func func={func} />;
}

const func: ScalarFuncType = JSON.parse("{\"name\":\"pow\",\"implemented\":true,\"desc\":\"Computes the result of raising the first argument to the power of the second argument. Both arguments must be numeric (f64 or i64), and the result is returned as an f64 value. Returns an error for negative bases with non-integer exponents.\",\"usage\":\"Raises a number to the specified power.\",\"category\":\"math\",\"signatures\":[{\"return_type\":\"scalar:f64\",\"arg_types\":[\"scalar:f64\",\"scalar:f64\"]},{\"return_type\":\"scalar:f64\",\"arg_types\":[\"scalar:f64\",\"scalar:i64\"]},{\"return_type\":\"scalar:f64\",\"arg_types\":[\"scalar:i64\",\"scalar:f64\"]},{\"return_type\":\"scalar:f64\",\"arg_types\":[\"scalar:i64\",\"scalar:i64\"]}],\"examples\":[{\"name\":\"pow(x, y), return 'x' raised to the power 'y'\",\"input\":[{\"machineId\":1,\"sessionId\":1,\"eventId\":1,\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\"}\"}],\"query\":\"project powOf2=pow(2, 10)\",\"output\":{\"tabular\":{\"freeForm\":{\"type\":{\"columns\":[{\"name\":\"powOf2\",\"type\":{\"scalar\":\"f64\"}}]},\"rows\":[{\"items\":[{\"type\":{\"scalar\":\"f64\"},\"f64\":1024}]}]}}}},{\"name\":\"pow(x, y), return 'x' raised to the power 'y'\",\"input\":[{\"machineId\":1,\"sessionId\":1,\"eventId\":1,\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\", \\\"x\\\": 2, \\\"y\\\": 0}\"},{\"machineId\":1,\"sessionId\":1,\"eventId\":2,\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\", \\\"x\\\": 2, \\\"y\\\": 1}\"},{\"machineId\":1,\"sessionId\":1,\"eventId\":3,\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\", \\\"x\\\": 2, \\\"y\\\": 2}\"},{\"machineId\":1,\"sessionId\":1,\"eventId\":4,\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\", \\\"x\\\": 2, \\\"y\\\": 3}\"}],\"query\":\"project powOf2=pow(['x'], ['y'])\",\"output\":{\"tabular\":{\"freeForm\":{\"type\":{\"columns\":[{\"name\":\"powOf2\",\"type\":{\"scalar\":\"f64\"}}]},\"rows\":[{\"items\":[{\"type\":{\"scalar\":\"f64\"},\"f64\":1}]},{\"items\":[{\"type\":{\"scalar\":\"f64\"},\"f64\":2}]},{\"items\":[{\"type\":{\"scalar\":\"f64\"},\"f64\":4}]},{\"items\":[{\"type\":{\"scalar\":\"f64\"},\"f64\":8}]}]}}}}]}") as ScalarFuncType;
