export default {
    TLD: '.dev',
    NEXT_PUBLIC_SIGNUP_ONLY: process.env.NEXT_PUBLIC_SIGNUP_ONLY === "true",
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_SELF_BASE_URL: process.env.NEXT_PUBLIC_SELF_BASE_URL,
    NEXT_PUBLIC_DEFAULT_RELEASE_CHANNEL: process.env.NEXT_PUBLIC_DEFAULT_RELEASE_CHANNEL,
};
