apiVersion: apps/v1
kind: Deployment
metadata:
  name: humanlog-deployment
  labels:
    app: humanlog
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: humanlog
  template:
    metadata:
      labels:
        app: humanlog
    spec:
      containers:
        - name: humanlog
          image: {{ .Values.app.deployment.registry }}/{{ .Values.app.deployment.image }}:{{ .Values.app.deployment.tag }}
          command:
          - node
          - server.js
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: "HOST"
              value: {{ .Values.app.host }}
            - name: "PORT"
              value: {{ .Values.app.port | quote }}
            - name: SELF_BASE_URL
              value: {{ .Values.app.self_base_url }}
            - name: API_BASE_URL
              value: {{ .Values.app.api_base_url }}
