app:
  replicas: 3
  host: "0.0.0.0"
  port: 3000
  self_base_url: https://humanlog.io
  api_base_url: https://api.humanlog.io
  deployment:
    registry: registry.digitalocean.com/humanlog
    image: humanlogio
    tag: <FILL_ME>
