import type { Metadata } from "next";
import { JetBrains_Mono as Font } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils"

const font = Font({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "humanlog.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          font.variable
        )}
      >{children}</body>
    </html>
  );
}
