#!/usr/bin/env bash

set -e

root=$(git rev-parse --show-toplevel)

dev_domain="app.humanlog.dev"
hostfile="/etc/hosts"
certdir="${root}/certificates"
cafile="${certdir}/rootCA.pem"
certfile="${certdir}/${dev_domain}.pem"
keyfile="${certdir}/${dev_domain}-key.pem"

function require_being_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "$0 is not running as root. Try using sudo."
        exit 2
    fi
}

function run_mkcert() {
    if [ -x "$(command -v mkcert)" ]; then
        mkcert "$@"
        return
    fi
    if [ -x "$(command -v pkgx)" ]; then
        pkgx mkcert "$@"
        return
    fi
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "installing mkcert"
        curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
        chmod +x mkcert-v*-linux-amd64
        sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
    fi
    mkcert  "$@"
    return
}

function hostfile_has_dev_domain() {
    grep < ${hostfile} "127.0.0.1 ${dev_domain}" > /dev/null
}

function install_dev_domain_in_hostfile() {
    printf "\n127.0.0.1 ${dev_domain}" >> ${hostfile}
}

function generate_and_install_self_signed_tls() {
    mkdir -p ${certdir}
    run_mkcert -install
    run_mkcert -cert-file ${certfile} -key-file ${keyfile} ${dev_domain} "*.${dev_domain}" localhost 127.0.0.1 ::1
    cp "$(run_mkcert -CAROOT)/rootCA.pem" ${cafile}
    chown -R $SUDO_USER ${certdir}
}

function main() {
    require_being_root
    if ! hostfile_has_dev_domain; then
        install_dev_domain_in_hostfile
        echo "changed: added ${dev_domain} to ${hostfile}"
    else
        echo "skipped: ${hostfile} already has ${dev_domain}"
    fi
    generate_and_install_self_signed_tls
}

main
