/**
 * @generated
 * This file is auto-generated. Do not edit manually.
 */

import { Func } from "@/components/docs/reference/funcs/Func";
import { ScalarFunc as ScalarFuncType } from "@/types/docs";

export default function Page() {
  return <Func func={func} />;
}

const func: ScalarFuncType = JSON.parse("{\"name\":\"isint\",\"implemented\":true,\"desc\":\"Determines whether the input value is an integer. Returns false if any other type.\",\"usage\":\"Tests whether a value is an integer.\",\"category\":\"validation\",\"signatures\":[{\"return_type\":\"scalar:bool\",\"arg_types\":[\"scalar:str\"]},{\"return_type\":\"scalar:bool\",\"arg_types\":[\"scalar:bool\"]},{\"return_type\":\"scalar:bool\",\"arg_types\":[\"scalar:f64\"]},{\"return_type\":\"scalar:bool\",\"arg_types\":[\"scalar:i64\"]},{\"return_type\":\"scalar:bool\",\"arg_types\":[\"scalar:dur\"]},{\"return_type\":\"scalar:bool\",\"arg_types\":[\"scalar:ts\"]}],\"examples\":[{\"name\":\"isint(x), return true if 'x' is an integer\",\"input\":[{\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\", \\\"x\\\": 1}\"},{\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\", \\\"x\\\": 2}\"}],\"query\":\"project isint=isint(['x'])\",\"output\":{\"freeForm\":{\"type\":{\"columns\":[{\"name\":\"isint\",\"type\":{\"scalar\":\"bool\"}}]},\"rows\":[{\"items\":[{\"type\":{\"scalar\":\"bool\"},\"bool\":true}]},{\"items\":[{\"type\":{\"scalar\":\"bool\"},\"bool\":true}]}]}}},{\"name\":\"isint(x), where 'x' is integer\",\"input\":[{\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\"}\"}],\"query\":\"project isint=isint(1)\",\"output\":{\"freeForm\":{\"type\":{\"columns\":[{\"name\":\"isint\",\"type\":{\"scalar\":\"bool\"}}]},\"rows\":[{\"items\":[{\"type\":{\"scalar\":\"bool\"},\"bool\":true}]}]}}},{\"name\":\"isint(x), where 'x' is a float\",\"input\":[{\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\"}\"}],\"query\":\"project isint=isint(1.0)\",\"output\":{\"freeForm\":{\"type\":{\"columns\":[{\"name\":\"isint\",\"type\":{\"scalar\":\"bool\"}}]},\"rows\":[{\"items\":[{\"type\":{\"scalar\":\"bool\"},\"bool\":false}]}]}}},{\"name\":\"isint(x), return false if 'x' is not an integer\",\"input\":[{\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\", \\\"x\\\": 0.1}\"},{\"parsedAt\":\"2006-01-02T15:04:06.001Z\",\"log\":\"{\\\"ts\\\":\\\"2006-01-02T15:04:06.001\\\", \\\"lvl\\\": \\\"info\\\", \\\"x\\\": 1.1}\"}],\"query\":\"project isint=isint(['x'])\",\"output\":{\"freeForm\":{\"type\":{\"columns\":[{\"name\":\"isint\",\"type\":{\"scalar\":\"bool\"}}]},\"rows\":[{\"items\":[{\"type\":{\"scalar\":\"bool\"},\"bool\":false}]},{\"items\":[{\"type\":{\"scalar\":\"bool\"},\"bool\":false}]}]}}}]}") as ScalarFuncType;
