name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pkgx
        uses: pkgxdev/setup@v1

      - name: Install
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Prepare testing
        run: sudo script/setup-localhost

      - name: Run unit tests
        run: npm run test:unit

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Build container image
        run: docker build -t registry.digitalocean.com/humanlog/humanlogio:$(echo $GITHUB_SHA | head -c7) .
