name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git for Private Repo Access
        run: |
          git config --global url."https://x-access-token:${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global --add url."https://x-access-token:${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}@github.com/".insteadOf "git@github.com:"

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Setup Localhost
        run: script/check-has-setup-localhost || sudo script/setup-localhost

      # TODO: disabled for now as we're breaking them all the time when trying new stuff
      # - name: Run Unit Tests
      #   run: npm run test:unit

      - name: Build Container Image
        run: script/build
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      # TODO: disabled for now as we're breaking them all the time when trying new stuff
      # and they take too long to run in CI
      # - name: Cache Playwright Browsers
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/ms-playwright
      #     key: ${{ runner.os }}-playwright-browsers
      # - name: Install Playwright Browsers
      #   run: |
      #     npx playwright install --with-deps
      #     sudo mkdir -p /usr/local/share/ca-certificates/humanlog
      #     sudo cp ./certificates/rootCA.pem /usr/local/share/ca-certificates/humanlog/
      #     sudo update-ca-certificates
      # - name: Run e2e Tests
      #   run: npm run test:e2e
