name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/setup@v1

      - name: Install deps
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Lint
        run: npm run lint

      - name: Prepare testing
        run: sudo script/setup-localhost

      - name: Run unit tests
        run: npm run test:unit

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Build container image
        run: docker build -t registry.digitalocean.com/humanlog/humanlogio:$(echo $GITHUB_SHA | head -c7) .
