name: 🚀 to prod

on:
  workflow_dispatch:

jobs:
  shipit:
    name: "🚀 to prod"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCN_REGISTRY_TOKEN }}

      - name: Install helm
        uses: azure/setup-helm@v4.2.0

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DOCN_K8S_CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: helm upgrade --install humanlogio ./deploy/app --namespace webapp  --values ./deploy/app/values.yaml --set "app.deployment.tag=$(echo $GITHUB_SHA | head -c7)"
